theme: jekyll-theme-leap-day
title: Fabricated
description: Yet another tech related mod pack!
show_downloads: true
github:
  zip_url: https://github.com/fabricated-pack/fabricated/releases/latest/download/Fabricated.zip